Add button with select English lvl
vladysllav/englishbot pull request #2
Opened 2023-06-10 14:50 UTC by AlexGrig23

Выполнил задачу в виде кнопок, если так не подойдет то поменяю на команды. Но мне кажется так интересней. Если апрувим такое то кнопку старт доработаю что бы сразу появлялась после запуска, а не после команды /start

2023-06-11 11:53 UTC, VaretsaK approved these changes

2023-06-14 10:47 UTC, vladysllav requested changes
request some changes

2023-06-14 10:47 UTC, vladysllav commented on src/main.py
> +        self.callback_handler = CallbackQueryHandler(self.handle_callback)
I think thats not the perfect place to keep that. Better to put that code directly in add_handler method

2023-06-14 10:47 UTC, vladysllav commented on src/main.py
> +    async def handle_callback(self, update: Update, context: CallbackContext):
FUnction name is bad. You dont need to use general names, specify the name depending on what that function suppose to do, for example choose_level_callback

2023-06-14 18:19 UTC, vladysllav approved these changes

2023-06-14 18:19 UTC, merged